site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md
    - Installation: installation.md
    - Making a C Function Asynchronous: c_async.md
    - Making Asynchronous Calls from C: adding_awaits.md
    - Storing and Fetching Values: storage.md

theme:
    name: readthedocs

markdown_extensions:
    - toc:
          permalink: true
    - admonition

plugins:
    - search
