site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md
    - Installation: installation.md
    - Awaiting Coroutines: awaiting.md
    - Callbacks: callbacks.md
    - Storing and Fetching Values: storage.md
    - Useful Utilities: utilities.md

theme:
    name: readthedocs

plugins:
    - search
