site_name: PyAwaitable
site_url: https://awaitable.zintensity.dev
repo_url: https://github.com/ZeroIntensity/pyawaitable
repo_name: ZeroIntensity/pyawaitable

nav:
    - Home: index.md
    - Installation: installation.md
    - Awaiting Coroutines: awaiting.md
    - Callbacks: callbacks.md
    - Storing and Fetching Values: storage.md
    - Useful Utilities: utilities.md

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          primary: black
          accent: light blue
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: light blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - content.tabs.link
        - content.code.copy
        - content.action.edit
        - search.highlight
        - search.share
        - search.suggest
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - toc.follow

    icon:
        repo: fontawesome/brands/github
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true

plugins:
    - search
