name: Improvement
description: 
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        # Improvement

        An improvement proposal should be related to an *existing* feature. For example, adding some functionality to the *existing* coroutine implementation.
  - type: textarea
    attributes:
      label: "Description:"
      description: >
        Outline what needs to be improved and why? Be sure to include an example API if necessary. 
      value: |
        ```c
        // Example API
        ```
    validations:
      required: true
