name: Tests

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'tests/**'
            - 'src/**'
            - '.github/workflows/tests.yml'
    pull_request:
        paths-ignore:
            - 'tests/**'
            - 'src/**'
            - '.github/workflows/tests.yml'

jobs:
    run-tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: "No-op the tests"
              run: 'echo "This change does not affect tests."'